-- Live page content blocks
-- Migrates hero, stream, chat, and schedule sections into CMS-editable content_blocks.

INSERT INTO content_blocks (section_key, title, subtitle, body, image, items, enabled, sort_order)
VALUES
  ('live_hero',
   'Join Us Live',
   'Can''t be with us in person? Worship along with our congregation from anywhere in the world.',
   NULL,
   NULL,
   '[{"eyebrow":"Live Stream"}]'::jsonb,
   TRUE,
   0),
  ('live_stream',
   'Sunday Celebration Service',
   'Join us for worship, the Word, and prayer. God is doing something beautiful \u2014 and you''re part of it.',
   NULL,
   NULL,
   '[{"badge":"LIVE"}]'::jsonb,
   TRUE,
   1),
  ('live_chat_heading',
   'Live Chat',
   NULL,
   NULL,
   NULL,
   '[{"placeholder":"Say something kind..."}]'::jsonb,
   TRUE,
   2),
  ('live_chat_messages',
   'Chat Messages',
   NULL,
   NULL,
   NULL,
   '[{"name":"Sunita","text":"Praise God! Worshipping from Pokhara \ud83d\ude4f"},{"name":"Ramesh","text":"Amen! Powerful message today."},{"name":"Kabita","text":"Blessings to everyone joining online \u2764\ufe0f"}]'::jsonb,
   TRUE,
   3),
  ('live_schedule',
   'Weekly Live Schedule',
   NULL,
   NULL,
   NULL,
   '[{"ctaLabel":"See All Events","ctaLink":"/events"}]'::jsonb,
   TRUE,
   4)
ON CONFLICT (section_key) DO NOTHING;
