-- Sermons page content blocks
-- Migrates hero, headings, search placeholder, and empty-state text into CMS-editable content_blocks.

INSERT INTO content_blocks (section_key, title, subtitle, body, image, items, enabled, sort_order)
VALUES
  ('sermons_hero',
   'Sermons',
   'Be encouraged and equipped by God''s Word — watch, listen or read at your convenience.',
   NULL,
   NULL,
   '[{"crumb":"Sermons"}]'::jsonb,
   TRUE,
   0),
  ('sermons_heading',
   'Sermons',
   NULL,
   NULL,
   NULL,
   '[{"eyebrow":"Browse & Listen","search_placeholder":"Search by title, speaker, series, or description..."}]'::jsonb,
   TRUE,
   1),
  ('sermons_description',
   'Search and discover messages that will strengthen your faith and walk with Christ.',
   NULL,
   NULL,
   NULL,
   '[]'::jsonb,
   TRUE,
   2),
  ('sermons_recent_heading',
   'Recent Sermons',
   NULL,
   NULL,
   NULL,
   '[{"eyebrow":"Watch & Listen"}]'::jsonb,
   TRUE,
   3),
  ('sermons_empty_state',
   'No sermons found',
   'Try adjusting your search or filters to find what you''re looking for.',
   NULL,
   NULL,
   '[{"btn_label":"Clear all filters"}]'::jsonb,
   TRUE,
   4),
  ('sermons_archive_heading',
   'Sermon Archive',
   NULL,
   NULL,
   NULL,
   '[{"eyebrow":"Previous Messages"}]'::jsonb,
   TRUE,
   5)
ON CONFLICT (section_key) DO NOTHING;
