ALTER TABLE donations ADD COLUMN IF NOT EXISTS refund_amount BIGINT NOT NULL DEFAULT 0;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS refund_status VARCHAR(20) NOT NULL DEFAULT 'none';
ALTER TABLE donations ADD COLUMN IF NOT EXISTS refunded_at TIMESTAMP;
ALTER TABLE donations ADD COLUMN IF NOT EXISTS refund_reason TEXT DEFAULT '';
ALTER TABLE donations ADD COLUMN IF NOT EXISTS gateway_refund_id VARCHAR(255);
