ALTER TABLE broadcasts ADD COLUMN IF NOT EXISTS scheduled_at TIMESTAMP;
ALTER TABLE broadcasts ADD COLUMN IF NOT EXISTS template_body TEXT NOT NULL DEFAULT '';
ALTER TABLE broadcast_recipients ADD COLUMN IF NOT EXISTS opened_at TIMESTAMP;
ALTER TABLE broadcast_recipients ADD COLUMN IF NOT EXISTS recipient_name VARCHAR(255) NOT NULL DEFAULT '';