use axum::routing::{delete, get, patch, post, put};
use axum::Router;

use crate::auth::AdminGuard;
use crate::handlers::*;

/// Public + read-only routes (no auth required).
fn public_routes() -> Router {
    Router::new()
        // Auth (public)
        .route("/auth/login", post(auth::login))
        // Content (public reads)
        .route("/sermons", get(sermons::list))
        .route("/sermons/{id}", get(sermons::get))
        .route("/ministries", get(ministries::list))
        .route("/ministries/{id}", get(ministries::get))
        .route("/events", get(events::list))
        .route("/events/{id}", get(events::get))
        .route("/leaders", get(leaders::list))
        .route("/leaders/{id}", get(leaders::get))
        .route("/gallery", get(gallery::list))
        .route("/gallery/{id}", get(gallery::get))
        .route("/testimonies", get(testimonies::list))
        .route("/testimonies/{id}", get(testimonies::get))
        .route("/notices", get(notices::list))
        .route("/notices/{id}", get(notices::get))
        .route("/members", get(members::list))
        .route("/members/{id}", get(members::get))
        .route("/service-times", get(service_times::list))
        .route("/service-times/{id}", get(service_times::get))
        .route("/verses", get(verses::list))
        .route("/verses/{id}", get(verses::get))
        .route("/campaigns", get(campaigns::list))
        .route("/campaigns/{id}", get(campaigns::get))
        .route("/settings", get(settings::list))
        .route("/settings/{key}", get(settings::get))
        .route("/settings/sections", get(settings::get_sections))
        .route("/uploads/{filename}", get(upload::serve_upload))
        .route("/content-blocks/enabled", get(content_blocks::list_enabled))
        .route("/content-blocks/key/{key}", get(content_blocks::get_by_key))
        .route("/blog", get(blog::list))
        .route("/blog/published", get(blog::list_published))
        .route("/blog/{id}", get(blog::get))
        .route("/services", get(services::list))
        .route("/services/{id}", get(services::get))
        .route("/team", get(team::list))
        .route("/team/{id}", get(team::get))
        .route("/newsletter/subscribe", post(newsletter::subscribe))
        .route("/newsletter/count", get(newsletter::count))
        .route("/portfolio", get(portfolio::list))
        .route("/portfolio/{id}", get(portfolio::get))
        .route("/contact-info", get(contact_info::list))
        .route("/contact-info/{id}", get(contact_info::get))
        .route("/contact-messages", post(contact_messages::create))
        .route("/groups", get(groups::list))
        .route("/groups/{id}", get(groups::get))
        .route("/dashboard/stats", get(dashboard::stats))
        .route("/people/stats", get(people::stats))
        .route("/offerings/stats", get(offerings::stats))
        .route("/donations/initiate", post(donations::initiate))
        .route("/donations/callback/esewa", get(donations::callback_esewa))
        .route("/donations/callback/khalti/{id}", post(donations::callback_khalti))
        .route("/donations/status", get(donations::status))
        .route("/donations/stats", get(donations::stats))
        .route("/events/{id}/rsvps", get(event_rsvps::list_by_event))
        .route("/forms/{id}/submit", post(forms::submit_public))
        .route("/reports/giving-summary", get(reports::giving_summary))
        .route("/reports/people-summary", get(reports::people_summary))
        .route("/member-applications", post(member_applications::create))
}

/// Authenticated user routes (any valid JWT, any role).
fn auth_routes() -> Router {
    Router::new()
        .route("/auth/me", get(auth::me).put(auth::update_me))
        .route("/auth/change-password", post(auth::change_password))
        .route("/auth/refresh", post(auth::refresh))
}

/// Admin-only routes (require role='admin').
/// These routes are protected by the AdminGuard extractor.
fn admin_routes() -> Router {
    Router::new()
        // Users (admin only)
        .route("/users", get(users::list).post(users::create))
        .route("/users/{id}", get(users::get).put(users::update).delete(users::delete))
        // Sermons
        .route("/sermons", post(sermons::create))
        .route("/sermons/{id}", put(sermons::update).delete(sermons::delete))
        .route("/sermons/{id}/toggle", put(sermons::toggle))
        .route("/sermons/{id}/reorder", put(sermons::reorder))
        // Ministries
        .route("/ministries", post(ministries::create))
        .route("/ministries/{id}", put(ministries::update).delete(ministries::delete))
        .route("/ministries/{id}/toggle", put(ministries::toggle))
        .route("/ministries/{id}/reorder", put(ministries::reorder))
        // Events
        .route("/events", post(events::create))
        .route("/events/{id}", put(events::update).delete(events::delete))
        .route("/events/{id}/toggle", put(events::toggle))
        .route("/events/{id}/reorder", put(events::reorder))
        // Leaders
        .route("/leaders", post(leaders::create))
        .route("/leaders/{id}", put(leaders::update).delete(leaders::delete))
        .route("/leaders/{id}/toggle", put(leaders::toggle))
        .route("/leaders/{id}/reorder", put(leaders::reorder))
        // Gallery
        .route("/gallery", post(gallery::create))
        .route("/gallery/{id}", put(gallery::update).delete(gallery::delete))
        .route("/gallery/{id}/toggle", put(gallery::toggle))
        .route("/gallery/{id}/reorder", put(gallery::reorder))
        // Testimonies
        .route("/testimonies", post(testimonies::create))
        .route("/testimonies/{id}", put(testimonies::update).delete(testimonies::delete))
        .route("/testimonies/{id}/toggle", put(testimonies::toggle))
        .route("/testimonies/{id}/reorder", put(testimonies::reorder))
        // Notices
        .route("/notices", post(notices::create))
        .route("/notices/{id}", put(notices::update).delete(notices::delete))
        .route("/notices/{id}/toggle", put(notices::toggle))
        .route("/notices/{id}/reorder", put(notices::reorder))
        // Members
        .route("/members", post(members::create))
        .route("/members/{id}", put(members::update).delete(members::delete))
        .route("/members/{id}/toggle", put(members::toggle))
        .route("/members/{id}/reorder", put(members::reorder))
        // Service Times
        .route("/service-times", post(service_times::create))
        .route("/service-times/{id}", put(service_times::update).delete(service_times::delete))
        .route("/service-times/{id}/toggle", put(service_times::toggle))
        .route("/service-times/{id}/reorder", put(service_times::reorder))
        // Verses
        .route("/verses", post(verses::create))
        .route("/verses/{id}", put(verses::update).delete(verses::delete))
        .route("/verses/{id}/toggle", put(verses::toggle))
        .route("/verses/{id}/reorder", put(verses::reorder))
        .route("/verses/{id}/pin", put(verses::pin))
        // Campaigns
        .route("/campaigns", post(campaigns::create))
        .route("/campaigns/{id}", put(campaigns::update).delete(campaigns::delete))
        .route("/campaigns/{id}/toggle", put(campaigns::toggle))
        .route("/campaigns/{id}/reorder", put(campaigns::reorder))
        // Settings (writes)
        .route("/settings/{key}", put(settings::upsert))
        .route("/settings/sections/{section}/toggle", put(settings::toggle_section))
        // Upload
        .route("/upload", post(upload::upload))
        .route("/uploads", get(upload::list_uploads))
        // Content Blocks
        .route("/content-blocks", get(content_blocks::list).post(content_blocks::create))
        .route("/content-blocks/reorder", patch(content_blocks::batch_reorder))
        .route("/content-blocks/{id}", get(content_blocks::get).put(content_blocks::update).delete(content_blocks::delete))
        .route("/content-blocks/{id}/toggle", put(content_blocks::toggle))
        .route("/content-blocks/{id}/reorder", put(content_blocks::reorder))
        // Donations (admin reads)
        .route("/donations", get(donations::list))
        .route("/donations/{id}", get(donations::get))
        .route("/donations/statements", get(donations::statements))
        .route("/donations/by-donor", get(donations::by_donor))
        .route("/donations/donor-history", get(donations::donor_history))
        // Todos
        .route("/todos", get(todos::list).post(todos::create))
        .route("/todos/{id}", get(todos::get).put(todos::update).delete(todos::delete))
        .route("/todos/{id}/toggle", put(todos::toggle_status))
        .route("/todos/{id}/reorder", put(todos::reorder))
        // Blog (admin writes)
        .route("/blog", post(blog::create))
        .route("/blog/{id}", put(blog::update).delete(blog::delete))
        // Services (admin writes)
        .route("/services", post(services::create))
        .route("/services/{id}", put(services::update).delete(services::delete).patch(services::update))
        .route("/services/{id}/toggle", put(services::toggle))
        .route("/services/{id}/reorder", put(services::reorder))
        // Team (admin writes)
        .route("/team", post(team::create))
        .route("/team/{id}", put(team::update).delete(team::delete))
        .route("/team/{id}/toggle", put(team::toggle))
        .route("/team/{id}/reorder", put(team::reorder))
        // Newsletter (admin)
        .route("/newsletter/subscribers", get(newsletter::list_subscribers))
        .route("/newsletter/unsubscribe/{email}", post(newsletter::unsubscribe))
        // Portfolio (admin writes)
        .route("/portfolio", post(portfolio::create))
        .route("/portfolio/{id}", put(portfolio::update).delete(portfolio::delete))
        .route("/portfolio/{id}/toggle", put(portfolio::toggle))
        .route("/portfolio/{id}/reorder", put(portfolio::reorder))
        // Contact Info (admin writes)
        .route("/contact-info", post(contact_info::create))
        .route("/contact-info/{id}", put(contact_info::update).delete(contact_info::delete))
        // Contact Messages (admin reads + management)
        .route("/contact-messages", get(contact_messages::list))
        .route("/contact-messages/{id}", get(contact_messages::get).delete(contact_messages::delete))
        .route("/contact-messages/{id}/read", put(contact_messages::mark_read))
        // Groups (admin writes)
        .route("/groups", post(groups::create))
        .route("/groups/{id}", put(groups::update).delete(groups::delete))
        .route("/groups/{id}/toggle", put(groups::toggle))
        .route("/groups/{id}/reorder", put(groups::reorder))
        // People (CRM)
        .route("/people", get(people::list).post(people::create))
        .route("/people/{id}", get(people::get).put(people::update).delete(people::delete))
        .route("/people/{id}/toggle", put(people::toggle))
        .route("/people/{id}/reorder", put(people::reorder))
        .route("/people/{id}/tags", get(people::get_person_tags))
        .route("/people/{id}/tags/{tag_id}", post(people::add_person_tag).delete(people::remove_person_tag))
        .route("/people/{id}/notes", get(people::list_person_notes).post(people::create_person_note))
        .route("/people/{id}/notes/{note_id}", delete(people::delete_person_note))
        // Households
        .route("/households", get(people::list_households).post(people::create_household))
        .route("/households/{id}", get(people::get_household).put(people::update_household).delete(people::delete_household))
        // Tags
        .route("/tags", get(people::list_tags).post(people::create_tag))
        .route("/tags/{id}", delete(people::delete_tag))
        // Group memberships
        .route("/groups/{id}/members", get(people::list_group_members).post(people::add_group_member))
        .route("/groups/{group_id}/members/{person_id}", delete(people::remove_group_member))
        // Offerings
        .route("/offerings", get(offerings::list).post(offerings::create))
        .route("/offerings/{id}", get(offerings::get).put(offerings::update).delete(offerings::delete))
        // Event RSVPs (admin)
        .route("/events/{id}/rsvps", post(event_rsvps::create_public))
        .route("/rsvps/{id}", delete(event_rsvps::delete))
        // Attendance
        .route("/attendance", get(attendance::list).post(attendance::check_in))
        .route("/attendance/stats", get(attendance::stats))
        // Broadcasts
        .route("/broadcasts", get(broadcasts::list).post(broadcasts::create))
        .route("/broadcasts/{id}", get(broadcasts::get).delete(broadcasts::delete))
        .route("/broadcasts/{id}/send", post(broadcasts::send))
        // Forms
        .route("/forms", get(forms::list).post(forms::create))
        .route("/forms/{id}", get(forms::get).put(forms::update).delete(forms::delete))
        .route("/forms/{id}/submissions", get(forms::list_submissions))
        // Volunteers
        .route("/volunteer-teams", get(volunteers::list_teams).post(volunteers::create_team))
        .route("/volunteer-teams/{id}", get(volunteers::get_team).put(volunteers::update_team).delete(volunteers::delete_team))
        .route("/volunteer-shifts", get(volunteers::list_shifts).post(volunteers::create_shift))
        .route("/volunteer-shifts/{id}", get(volunteers::get_shift).put(volunteers::update_shift).delete(volunteers::delete_shift))
        .route("/volunteer-shifts/{id}/assignments", get(volunteers::list_assignments).post(volunteers::create_assignment))
        // Audit Log
        .route("/audit-log", get(audit::list))
        // Funds
        .route("/funds", get(funds::list).post(funds::create))
        .route("/funds/{id}", get(funds::get).put(funds::update).delete(funds::delete))
        .route("/recurring-donations", get(funds::list_recurring).post(funds::create_recurring))
        // Pledges
        .route("/pledges", get(pledges::list_all).post(pledges::create))
        .route("/pledges/{id}", get(pledges::get).put(pledges::update).delete(pledges::delete))
        .route("/campaigns/{id}/pledges", get(pledges::list_by_campaign))
        // Member Applications (admin management)
        .route("/member-applications", get(member_applications::list))
        .route("/member-applications/stats", get(member_applications::stats))
        .route("/member-applications/{id}", get(member_applications::get).put(member_applications::update).delete(member_applications::delete))
}

/// State-agnostic: handlers resolve their per-tenant DB pool via the `Db`
/// extractor (populated by tenant middleware), so the router needs no state.
pub fn api_routes() -> Router {
    // Admin routes wrapped with AdminGuard middleware
    let guarded_admin = admin_routes()
        .layer(axum::middleware::from_extractor::<AdminGuard>());

    Router::new()
        .merge(public_routes())
        .merge(auth_routes())
        .merge(guarded_admin)
}
