use axum::routing::{delete, get, patch, post, put};
use axum::Router;

use crate::handlers::*;

// State-agnostic: handlers resolve their per-tenant DB pool via the `Db`
// extractor (populated by tenant middleware), so the router needs no state.
pub fn api_routes() -> Router {
    Router::new()
        // Auth
        .route("/auth/login", post(auth::login))
        .route("/auth/register", post(auth::register))
        .route("/auth/me", get(auth::me).put(auth::update_me))
        .route("/auth/change-password", post(auth::change_password))
        // Users (admin only)
        .route("/users", get(users::list).post(users::create))
        .route("/users/{id}", get(users::get).put(users::update).delete(users::delete))
        // Sermons
        .route("/sermons", get(sermons::list).post(sermons::create))
        .route("/sermons/{id}", get(sermons::get).put(sermons::update).delete(sermons::delete))
        .route("/sermons/{id}/toggle", put(sermons::toggle))
        .route("/sermons/{id}/reorder", put(sermons::reorder))
        // Ministries
        .route("/ministries", get(ministries::list).post(ministries::create))
        .route("/ministries/{id}", get(ministries::get).put(ministries::update).delete(ministries::delete))
        .route("/ministries/{id}/toggle", put(ministries::toggle))
        .route("/ministries/{id}/reorder", put(ministries::reorder))
        // Events
        .route("/events", get(events::list).post(events::create))
        .route("/events/{id}", get(events::get).put(events::update).delete(events::delete))
        .route("/events/{id}/toggle", put(events::toggle))
        .route("/events/{id}/reorder", put(events::reorder))
        // Leaders
        .route("/leaders", get(leaders::list).post(leaders::create))
        .route("/leaders/{id}", get(leaders::get).put(leaders::update).delete(leaders::delete))
        .route("/leaders/{id}/toggle", put(leaders::toggle))
        .route("/leaders/{id}/reorder", put(leaders::reorder))
        // Gallery
        .route("/gallery", get(gallery::list).post(gallery::create))
        .route("/gallery/{id}", get(gallery::get).put(gallery::update).delete(gallery::delete))
        .route("/gallery/{id}/toggle", put(gallery::toggle))
        .route("/gallery/{id}/reorder", put(gallery::reorder))
        // Testimonies
        .route("/testimonies", get(testimonies::list).post(testimonies::create))
        .route("/testimonies/{id}", get(testimonies::get).put(testimonies::update).delete(testimonies::delete))
        .route("/testimonies/{id}/toggle", put(testimonies::toggle))
        .route("/testimonies/{id}/reorder", put(testimonies::reorder))
        // Notices
        .route("/notices", get(notices::list).post(notices::create))
        .route("/notices/{id}", get(notices::get).put(notices::update).delete(notices::delete))
        .route("/notices/{id}/toggle", put(notices::toggle))
        .route("/notices/{id}/reorder", put(notices::reorder))
        // Members
        .route("/members", get(members::list).post(members::create))
        .route("/members/{id}", get(members::get).put(members::update).delete(members::delete))
        .route("/members/{id}/toggle", put(members::toggle))
        .route("/members/{id}/reorder", put(members::reorder))
        // Service Times
        .route("/service-times", get(service_times::list).post(service_times::create))
        .route("/service-times/{id}", get(service_times::get).put(service_times::update).delete(service_times::delete))
        .route("/service-times/{id}/toggle", put(service_times::toggle))
        .route("/service-times/{id}/reorder", put(service_times::reorder))
        // Verses
        .route("/verses", get(verses::list).post(verses::create))
        .route("/verses/{id}", get(verses::get).put(verses::update).delete(verses::delete))
        .route("/verses/{id}/toggle", put(verses::toggle))
        .route("/verses/{id}/reorder", put(verses::reorder))
        // Campaigns
        .route("/campaigns", get(campaigns::list).post(campaigns::create))
        .route("/campaigns/{id}", get(campaigns::get).put(campaigns::update).delete(campaigns::delete))
        .route("/campaigns/{id}/toggle", put(campaigns::toggle))
        .route("/campaigns/{id}/reorder", put(campaigns::reorder))
        // Settings
        .route("/settings", get(settings::list))
        .route("/settings/{key}", get(settings::get).put(settings::upsert))
        .route("/settings/sections", get(settings::get_sections))
        .route("/settings/sections/{section}/toggle", put(settings::toggle_section))
        // Upload
        .route("/upload", post(upload::upload))
        .route("/uploads", get(upload::list_uploads))
        // Content Blocks — static paths MUST come before /{id} in Axum 0.8
        .route("/content-blocks", get(content_blocks::list).post(content_blocks::create))
        .route("/content-blocks/reorder", patch(content_blocks::batch_reorder))
        .route("/content-blocks/enabled", get(content_blocks::list_enabled))
        .route("/content-blocks/key/{key}", get(content_blocks::get_by_key))
        .route("/content-blocks/{id}", get(content_blocks::get).put(content_blocks::update).delete(content_blocks::delete))
        .route("/content-blocks/{id}/toggle", put(content_blocks::toggle))
        .route("/content-blocks/{id}/reorder", put(content_blocks::reorder))
        // Donations
        .route("/donations/initiate", post(donations::initiate))
        .route("/donations/callback/esewa", get(donations::callback_esewa))
        .route("/donations/callback/khalti/{id}", post(donations::callback_khalti))
        .route("/donations/status", get(donations::status))
        .route("/donations/stats", get(donations::stats))
        .route("/donations/statements", get(donations::statements))
        .route("/donations/by-donor", get(donations::by_donor))
        .route("/donations/donor-history", get(donations::donor_history))
        .route("/donations", get(donations::list))
        .route("/donations/{id}", get(donations::get))
        // Todos
        .route("/todos", get(todos::list).post(todos::create))
        .route("/todos/{id}", get(todos::get).put(todos::update).delete(todos::delete))
        .route("/todos/{id}/toggle", put(todos::toggle_status))
        .route("/todos/{id}/reorder", put(todos::reorder))
        // Blog
        .route("/blog", get(blog::list).post(blog::create))
        .route("/blog/published", get(blog::list_published))
        .route("/blog/{id}", get(blog::get).put(blog::update).delete(blog::delete))
        // Services
        .route("/services", get(services::list).post(services::create))
        .route("/services/{id}", get(services::get).put(services::update).delete(services::delete).patch(services::update))
        .route("/services/{id}/toggle", put(services::toggle))
        .route("/services/{id}/reorder", put(services::reorder))
        // Team
        .route("/team", get(team::list).post(team::create))
        .route("/team/{id}", get(team::get).put(team::update).delete(team::delete))
        .route("/team/{id}/toggle", put(team::toggle))
        .route("/team/{id}/reorder", put(team::reorder))
        // Newsletter
        .route("/newsletter/subscribers", get(newsletter::list_subscribers))
        .route("/newsletter/count", get(newsletter::count))
        .route("/newsletter/subscribe", post(newsletter::subscribe))
        .route("/newsletter/unsubscribe/{email}", post(newsletter::unsubscribe))
        // Portfolio
        .route("/portfolio", get(portfolio::list).post(portfolio::create))
        .route("/portfolio/{id}", get(portfolio::get).put(portfolio::update).delete(portfolio::delete))
        .route("/portfolio/{id}/toggle", put(portfolio::toggle))
        .route("/portfolio/{id}/reorder", put(portfolio::reorder))
        // Contact Info
        .route("/contact-info", get(contact_info::list).post(contact_info::create))
        .route("/contact-info/{id}", get(contact_info::get).put(contact_info::update).delete(contact_info::delete))
        // Contact Messages (prayer requests, visit inquiries)
        .route("/contact-messages", get(contact_messages::list).post(contact_messages::create))
        .route("/contact-messages/{id}", get(contact_messages::get).delete(contact_messages::delete))
        .route("/contact-messages/{id}/read", put(contact_messages::mark_read))
        // Groups
        .route("/groups", get(groups::list).post(groups::create))
        .route("/groups/{id}", get(groups::get).put(groups::update).delete(groups::delete))
        .route("/groups/{id}/toggle", put(groups::toggle))
        .route("/groups/{id}/reorder", put(groups::reorder))
        // Dashboard
        .route("/dashboard/stats", get(dashboard::stats))
        // People (CRM)
        .route("/people", get(people::list).post(people::create))
        .route("/people/stats", get(people::stats))
        .route("/people/{id}", get(people::get).put(people::update).delete(people::delete))
        .route("/people/{id}/toggle", put(people::toggle))
        .route("/people/{id}/reorder", put(people::reorder))
        .route("/people/{id}/tags", get(people::get_person_tags))
        .route("/people/{id}/tags/{tag_id}", post(people::add_person_tag).delete(people::remove_person_tag))
        .route("/people/{id}/notes", get(people::list_person_notes).post(people::create_person_note))
        .route("/people/{id}/notes/{note_id}", delete(people::delete_person_note))
        // Households
        .route("/households", get(people::list_households).post(people::create_household))
        .route("/households/{id}", get(people::get_household).put(people::update_household).delete(people::delete_household))
        // Tags
        .route("/tags", get(people::list_tags).post(people::create_tag))
        .route("/tags/{id}", delete(people::delete_tag))
        // Group memberships
        .route("/groups/{id}/members", get(people::list_group_members).post(people::add_group_member))
        .route("/groups/{group_id}/members/{person_id}", delete(people::remove_group_member))
        // Offerings
        .route("/offerings", get(offerings::list).post(offerings::create))
        .route("/offerings/stats", get(offerings::stats))
        .route("/offerings/{id}", get(offerings::get).put(offerings::update).delete(offerings::delete))
        // === NEW FEATURES ===
        // Event RSVPs
        .route("/events/{id}/rsvps", get(event_rsvps::list_by_event).post(event_rsvps::create_public))
        .route("/rsvps/{id}", delete(event_rsvps::delete))
        // Attendance
        .route("/attendance", get(attendance::list).post(attendance::check_in))
        .route("/attendance/stats", get(attendance::stats))
        // Broadcasts
        .route("/broadcasts", get(broadcasts::list).post(broadcasts::create))
        .route("/broadcasts/{id}", get(broadcasts::get).delete(broadcasts::delete))
        .route("/broadcasts/{id}/send", post(broadcasts::send))
        // Forms
        .route("/forms", get(forms::list).post(forms::create))
        .route("/forms/{id}", get(forms::get).put(forms::update).delete(forms::delete))
        .route("/forms/{id}/submit", post(forms::submit_public))
        .route("/forms/{id}/submissions", get(forms::list_submissions))
        // Volunteers
        .route("/volunteer-teams", get(volunteers::list_teams).post(volunteers::create_team))
        .route("/volunteer-teams/{id}", get(volunteers::get_team).put(volunteers::update_team).delete(volunteers::delete_team))
        .route("/volunteer-shifts", get(volunteers::list_shifts).post(volunteers::create_shift))
        .route("/volunteer-shifts/{id}", get(volunteers::get_shift).put(volunteers::update_shift).delete(volunteers::delete_shift))
        .route("/volunteer-shifts/{id}/assignments", get(volunteers::list_assignments).post(volunteers::create_assignment))
        // Audit Log
        .route("/audit-log", get(audit::list))
        // Funds
        .route("/funds", get(funds::list).post(funds::create))
        .route("/funds/{id}", get(funds::get).put(funds::update).delete(funds::delete))
        .route("/recurring-donations", get(funds::list_recurring).post(funds::create_recurring))
        // Pledges
        .route("/pledges", get(pledges::list_all).post(pledges::create))
        .route("/pledges/{id}", get(pledges::get).put(pledges::update).delete(pledges::delete))
        .route("/campaigns/{id}/pledges", get(pledges::list_by_campaign))
        // Reports
        .route("/reports/giving-summary", get(reports::giving_summary))
        .route("/reports/people-summary", get(reports::people_summary))
        // Member Applications
        .route("/member-applications", get(member_applications::list).post(member_applications::create))
        .route("/member-applications/stats", get(member_applications::stats))
        .route("/member-applications/{id}", get(member_applications::get).put(member_applications::update).delete(member_applications::delete))
}
